image:
  file: dockerfile  
tasks:
  - init: npm install -g @angular/cli && mkdir hello-world && cd hello-world && ng new hello-world && ng serve -o  
ports:
  - port: 8000
    onOpen: open-preview    
  - port: 4200
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
